[project]
name = "energy_code_challege"
version = "0.0.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pytest>=8.3.3",
]

[tool.pytest.ini_options]
pythonpath = "src"